[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
stivale-boot = { path = "../third-party/stivale" }
log = "^0.4"
xmas-elf = "^0.8"
